# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11bd6de680f80c03ab6651f2dbe3b20bf907e5267f6c7c0b3cd2cbc8b322d3a4c1c368fd6c087df1d8561d820992ee7674078fdef810dd43f65cac2bb2882ce4

test:
  secret_key_base: eb27bdb44a785f9ddd53687c758d52ad02256fd2c55aa7814921f033d3f191fb48d042955a78a4c0821b5cdfd464699feebffdf17745354f8255f11f2e320d70

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
